### ISSUE TITLE
asyncValidate bug: Uncaught (in promise)

### ISSUE THREAD

**Issue by bertho-zero** [erikras/redux-form#1737]
Hello,

I use the method `asyncValidate` and no matter how I return my errors it returns me an error.

I have a simple function like the following and any of the following methods works:

```js
export function asyncValidate( values, dispatch ) {
  return Promise.reject( {slug: 'merde'} );
  // return Promise.resolve( {slug: 'merde'} );
  // return new Promise( {slug: 'merde'} );
  // throw {slug: 'merde'};
  // return { slug: 'merde' };
}
```

The error displayed in  console:
```
Uncaught (in promise) Object {slug: "MERDE"}
```

**Comment by Guria** [comment]
Try:
`return new Promise((resolve, reject) => reject(errors))`

**Comment by Guria** [comment]
It is only way that worked for me

**Comment by RazerM** [comment]
@Guria That doesn't work for me. It's essentially doing the same thing, no?

**Comment by skolmer** [comment]
I think this is duplicate of #1704 and #1297 
It _should_ be fixed in the next version because #1722 got merged

**Comment by erikras** [comment]
#1722 was just published in [`v6.0.3`](https://github.com/erikras/redux-form/releases/tag/v6.0.3).

Reopen if this is still a problem.

**Comment by caiobalthazar** [comment]
Are we supposed to be seeing this `Uncaught` error on 6.0.5? 
I am still getting those, even the website's example is throwing those up.
It seems something is still wrong. Screenshot attached.
![screenshot 2016-09-18 00 23 41](https://cloud.githubusercontent.com/assets/7861951/18612677/8aa60c90-7d36-11e6-9801-162a657c21b3.png)

**Comment by skolmer** [comment]
@caiobalthazar this is still an issue, you can subscribe to #1297 for further updates

**Comment by jainniket** [comment]
I'm still facing this issue *Uncaught (in promise)* in asyncValidation.

Waiting for its fix.

**Comment by skolmer** [comment]
@jainniket this was fixed in v6.1.0 #1297

**Comment by pmyagkov** [comment]
Reproducing in v6.1.1

**Comment by jelteliekens** [comment]
Still not fixed here in v6.2.0

**Comment by smiller393** [comment]
Reproducing in 6.5, even the website's example. Does anyone have a fix for this?

**Comment by leopsos** [comment]
Still reproducing in 6.7, with the website example at:
http://redux-form.com/6.7.0/examples/asyncValidation/
