### ISSUE TITLE
Uncaught Error: You must either pass handleSubmit() an onSubmit function or pass onSubmit as a prop

### ISSUE THREAD

**Issue by francorisso** [erikras/redux-form#190]
I'm using this example [here](http://erikras.github.io/redux-form/#/examples/simple?_k=4r1447), and I get this error:

`Uncaught Error: You must either pass handleSubmit() an onSubmit function or pass onSubmit as a prop`

I'm using this with redux-form 3, and I'm using a Modal to display the content, is a dumb component, so is not connected to redux.
Is there anything I'm missing here?

Thanks!

**Comment by francorisso** [comment]
My bad!, 
if someone is having the same issue is because the lack of the onSubmit action in the props of the components.

**Comment by sidazhou** [comment]
Running into the same problem, can you elaborate on the solution?

**Comment by ashwinvandijk** [comment]
@sidazhou, the way I fixed it, is to pass a function to the handleSubmit function provided by redux-form:
`<form onSubmit={handleSubmit(this.myOwnFunction)}>`.

**Comment by sidazhou** [comment]
I've understood what was the problem:
`onSubmit` **has to** be defined on the parent of the form

    <Parent>
      <Child onSubmit={myFunc}>
    </Parent>

You would expect the child 

    <Child> 
      <form></form>
    </Child>

has `this.props.onSubmit` to be available to you. However, redux-form changes it to `this.props.handleSubmit` instead. To reiterate, in the Child, `this.props.handleSubmit == myFunc`

**Comment by dtothefp** [comment]
The documentation...or lack there of, on this is super annoying. Just to be clear for others with this problem I did below which works

```js
import React, {Component, PropTypes} from 'react';
import {reduxForm} from 'redux-form';

class ContactForm extends Component {
  static propTypes = {
    handleSubmit: PropTypes.func,
    fields: PropTypes.object
  }

  handleSubmit(e) {
    //do stuff here
  }

  render() {
    const {fields: {firstName, lastName, email}, handleSubmit} = this.props;

    return (
      <form onSubmit={handleSubmit(this.handleSubmit)}>
        <div>
          <label>First Name</label>
          <input type="text" placeholder="First Name" {...firstName}/>
        </div>
        <div>
          <label>Last Name</label>
          <input type="text" placeholder="Last Name" {...lastName}/>
        </div>
        <div>
          <label>Email</label>
          <input type="email" placeholder="Email" {...email}/>
        </div>
        <button type="submit">Submit</button>
      </form>
    );
  }
}

// Decorate the form component
export default reduxForm({
  form: 'contact', // a unique name for this form
  fields: ['firstName', 'lastName', 'email']
})(ContactForm);
```

Don't be fooled and do the intuitive thing which would be to define a prop of `handleSubmit` on your instantiated JSX `<ContactForm handleSubmit={myFunc}>` 😢

**Comment by erikras** [comment]
> Don't be fooled and do the intuitive thing which would be to define a prop of handleSubmit on your instantiated JSX `<ContactForm handleSubmit={myFunc}>` 😢

This is why the FAQs mention [the difference between `onX` and `handleX`](http://redux-form.com/5.2.5/#/faq/handle-vs-on).

**Comment by 4pr3x** [comment]
Thanks to the hint from @dtothefp I was able to nearly solve the issue also for the wizard example. On the Third WizardPage I´m catching the submit call. But I still get the Error "Required prop `onSubmit` was not specified in ...". I guess this is based on the problem that I should have to route the event up the FormWizard Parent Component. I tried several things, but I don´t get it working without the Warning. Could someone point out how to do it or even If the idea of the event-routing up to Parent Component is correct?

**Comment by jinxac** [comment]
If you are using containers in this case, do check if you are returning Onsubmit function from mapDispatchtoProps.

**Comment by EnriqueSalazar** [comment]
I'll write it here again because is how I finally understood it and maybe is easier for other beginners as myself.

This is what worked for me:

```
import React, {Component} from 'react';
import {Field, reduxForm} from 'redux-form';
import {
  Button,
  
} from 'react-bootstrap';
import InputField from '../InputField';

let Modificador = props => {

  const {
    initialValues,
    mySubmit,
    handleSubmit
  }= props;

  return (
    <form onSubmit={handleSubmit(mySubmit)}>
       <Field
              name="nombre"
              label="Nombre"
              type="text"
              component={InputField}
            />
            <Button
              type="submit"
              bsStyle="primary">
              {"Guardar "}
              <Glyphicon glyph="floppy-save"/>
            </Button>
    </form>
  );
};

Modificador = reduxForm({
  form: 'modificadorForm',
  })(Modificador);

export default Modificador;
```

The parent
```
   <Modificador
            initialValues={values}
            mySubmit={submitFunction}
/>
```

**Comment by nneal** [comment]
I had this problem because I had my `Form` as a pure functions (rather than an es6 class). Switched to class and all works. Reason is because `handleSubmit` appears to call `this.props`

**Comment by ashishchauhan1** [comment]
@EnriqueSalaza code started working after gone through your example

**Comment by kesiena115** [comment]
@EnriqueSalazar Thank you so much for calling your submit function `mySubmit` instead of `handleSubmit` or `onSubmit`. This is perhaps one of the main reason why most other examples I've read were very confusing until I read yours.

In general, I feel like all the examples I've read contain too many occurrences of the word `submit`. It becomes too easy to mix up `submit`, `handleSubmit`, `onSubmit`, `"submit"`, etc. After seeing `submit` about 5 times (with slightly different prefixes and suffixes), it becomes too easy to miss some variables/functions and end up confused.

**Comment by facuch19** [comment]
@dtothefp Thank you so much bro. Really thanks, it was driving my crazy jaja xD

**Comment by mandajoan** [comment]
This I bound my form handler (handleFormSubmit) to the handleSubmit:

    const handleSubmit = this.props

     <form onSubmit={handleSubmit(this.handleFormSubmit.bind(this))}>

**Comment by nrion** [comment]
I wouldn't have understood where handleSubmit came from if I hadn't viewed this example: https://codesandbox.io/s/mZRjw05yp

**Comment by ShubhamKushwah** [comment]
I am getting the same error!
What if I need to pass an action creator to handleSubmit like this:
```
<form onSubmit={handleSubmit(this.props.ActionCreator)}>
</form>
...
...
export default reduxForm({
  form: 'bar',
  fields: ['foo', 'foo2', 'foo3']
}, null, {ActionCreator})(loremContainer);
```
Please help!

**Comment by ike76** [comment]
I got this error too, I _thought_ I was passing a function to handleSubmit()  but i was passing it some other garbage.  
  `handleSubmit(someOtherGarbage)`
I realized my error when i just passed it a function.
`handleSubmit( stuff => console.log(stuff) )`
...and suddenly there were all my form outputs in the console. 
solution:   I had a typo in my action creator.  duh.

**Comment by chris-fa** [comment]
If this is so different than what the docs explain, why has the docs never been updated?

**Comment by moffsugita** [comment]
@EnriqueSalazar 
Thank you. 

```<form onSubmit={handleSubmit(mySubmit)}>```
it was important for me. `handleSubmit(mySubmit) <---- important`

**Comment by adamfaryna** [comment]
> Hmm i am getting this error in a `Remote Submit` occasion in `v7.4.2`. I call it like this:
> 
> ```js
> this.props.dispatch(submit('myFormName'));
> ```
> 
> and my form is this:
> 
> ```js
> <form onSubmit={handleSubmit(this.handleSubmit)}>
> ...
> </form>
> ```

I stumble upon the same issue. It looks like bug.

**Comment by jasperkuperus** [comment]
I had the same issue as @adamfaryna and @fakiolinho and got this error in a remote submit. In my case, I accidentally had two different components that both initialized with the same form name (`reduxForm({ form: 'myForm' })(...)`). Some left-overs after refactoring. Removing one of these two `reduxForm` call fixed it for me. Hope this helps someone.

**Comment by dfalt** [comment]
@fakiolinho, @adamfaryna, @jasperkuperus and anyone else having a similar issue trying to pass an `onSubmit` handler to `handleSubmit` like:

```
<form onSubmit={handleSubmit(this.onSubmit)}>
...
</form>
```

I believe the solution is to use the [`Form` component](https://redux-form.com/8.1.0/docs/api/form.md/) which was added in version 6.4.0 (at least according to the docs). Switching out `<form>` for `<Form>` immediately resolved my issue, and the documentation seems to support that this is the component's intended use case:

> The Form component is a simple wrapper for the React <form> component that allows the surrounding redux-form-decorated component to trigger its onSubmit function.
>
> It is only useful if you are:
>
> * performing your submission from inside your form component by passing onSubmit={this.props.handleSubmit(this.mySubmitFunction)} to your <form> component
> * AND EITHER:
>     * initiating your submission via the submit() Instance API (i.e. calling it directly on a reference to your decorated form component)
>     * initiating your submission by dispatching the submit(form) action

**Comment by nikola1970** [comment]
@dfalt Thanks! Works well!
