### ISSUE TITLE
[blur event] Why does handleBlur updates field value?

### ISSUE THREAD

**Issue by mereskin** [erikras/redux-form#2768]
### What is the current behavior?

onBlur and onFocus callbacks are required to mark field as touched to display per-field validation. onBlur and onFocus assume DOM event is passed and current field value corresponds to value of the underlying DOM element.

That behavior is not working for custom components. If custom component is used in place of input the `value` property of DOM element that originates event can not be equal to that of a component itself. 

For example, we use `CheckBoxGroup` which has `value` proptype as `arrayOf(string)`. This component still emits onFocus and onBlur events when individual checkboxes are checked/unchecked and passes DOM event through. This DOM event is used by blur, value is extracted from it and this value is no longer an array but string `true`, since this value is read from `checked` property of a checkbox.

### What is the expected behavior?

onBlur event handler shouldn't update the value of the field and shouldn't assume that event object passed in is actually a DOM event. onBlur handler should update `touched` property of the field so that validation is still displayed.

Is there any reason why onBlur event updates form state? Can we use `onChange` events exclusively to update form state?

### What's your environment?
All environments

**Comment by carlsverre** [comment]
I am also having an issue with Blur modifying the value of the field.  The problem for me is that onBlur assumes that the event contains the current value - which is not true when you batch react updates and the form is updated via autocomplete.  In this case the browser fires `onChange` and `onBlur` in the same frame and thus the `onBlur` will see the "last" value of the field since the HTML input hasn't actually had a chance to update.

Making `onBlur` not update the form value will resolve my problem.

**Comment by carlsverre** [comment]
I am currently getting around this issue by calling the `onBlur` handler with no event argument.  This is supported by the tests and seems to do exactly what we want.  You can see the test here:

https://github.com/erikras/redux-form/blob/master/src/__tests__/reducer.blur.spec.js#L70

**Comment by shodanuk** [comment]
Another workaround is to use the parse (and / or possibly normalize) prop of Field to force the type value of that the blur action sets into state.

In my case, redux-form was converting number values of my fields into strings, causing issues with custom react-numeric input fields. [Line 99 of ConnectedField](https://github.com/erikras/redux-form/blob/892f45b5325fa7274cb6f8f0e7b3ea617b960c29/src/ConnectedField.js#L99) calls onChangeValue which "normalises" the value of the field using a function passed into the parse or normalize prop of ConnectField. In the absence of these functions being specified, the value seems to default to a string.

For what's worth, this is all I passed into the parse prop:

```
<Field
  ...
  parse={(value) => (parseInt(value, 10))}
  ...
  /> 
```
For it's worth, I agree with OP that the value being changed on a blur event is an unexpected and unconventional side effect that should considered for removal unless there's a really good reason for it.

**Comment by mereskin** [comment]
@carlsverre I tried your workaround: `onBlur={() => { input.onBlur(); }}` but it just clears the field in my case.

@erikras any objections to removing the value from `onBlur`? I could make a PR.

**Comment by mereskin** [comment]
@shodanuk this is assuming that value is of another type but still correct. This may be true for fields that imitate `input` but this is not the case for complex fields, like `CheckBoxGroup` that I described above.

Such field consists of multiple checkboxes. onBlur is emitted with `e` where `e.target` is an individual checkbox that originated an event. There is no corresponding DOM element that exposes correct `value` (array of strings) that can be supplied with `e.target`.

**Comment by carlsverre** [comment]
As far as I can tell the fact that blur changes the value has been the case since the 0.7 release of the project (earliest reference I could find to setting an onBlur handler for any form component).  You can see the code here:

https://github.com/erikras/redux-form/blob/e9b462cbb41bd8df3d27495c9911b9a2155d9b4e/src/reduxForm.js#L26

I don't see any issues or comments mentioning why the blur event does this in the entire history of the project.  I briefly looked at almost every commit which touched any of the blur code.

Would really appreciate a comment from @erikras on why Blur changes the value.

**Comment by erikras** [comment]
Hmm... Blur changes the value to allow maximum flexibility in how the library is used.

Can we be guaranteed that every single input that calls `onBlur` also calls `onChange` on every change? No, we can't. I know for a fact that some people have written inputs to work with `redux-form` that, to save on Redux traffic – especially for complex structures, like Draft.js wysiwyg editors – keep the value in local state and only send the value to Redux `onBlur`.

However, I definitely see why someone might want to only flip the `focus` and `touched` flags `onBlur`. What if we allowed a second `noUpdate` parameter to `onBlur`, so that you could do:

```jsx
<input {...props.input} onBlur={() => props.input.onBlur(undefined, true)}/>
```
 Or optionally one could pass a `noUpdateOnBlur` flag to `Field` that would do this for you.

```jsx
<Field name="firstName" component={renderInput} noUpdateOnBlur/>
```
I don't think that stripping the current value-setting functionality out of `onBlur`, like #2791 is doing, is the answer.

**Comment by mereskin** [comment]
I see. I think it would be straightforward for those components to implement something like:
```
onBlur={() => {
  input.onChange('some new value');
  input.onBlur();
})
```

Anyway. Maybe we shouldn't go as far as having a separate flag for `noUpdate` and instead just fix when `onBlur` is called without an event argument. 

Current behavior: 
if `onBlur` is called without `event` argument field's value will be set to `undefined`. 

Desired behavior:
If `onBlur` is called without `event` argument, set `touched` to `true` and don't change the value.

What do you think @erikras ?

**Comment by carlsverre** [comment]
If current consumers of the library are depending on various forms of the existing onBlur behavior - it will be a lot safer/faster for us to add a *new* mode rather than modifying the existing behavior.  In that case my vote is for supporting a second explicit parameter to the onBlur method.  Possibly it should be an options parameter to make future upgrades non-breaking as well:

```
function onBlur(event, options) {
  const { noUpdateValue } = options;
  ...
}```

**Comment by joshbedo** [comment]
Is there any fix for this right now? I'm using parse/format and any onblur event causes the field to be emptied.

**Comment by erikras** [comment]
> Current behavior:
if `onBlur` is called without event argument field's value is set to `undefined`.
> 
> Desired behavior:
If `onBlur` is called without event argument, set `touched` to `true` and don't change the value.

@mereskin I could be misunderstanding you, but this is not true. Calling `input.onBlur()` with no parameters does _not_ change the value. See: https://github.com/erikras/redux-form/commit/6aec0c45eb7acbcb12eb8e49e0feeeca2897597d

I must be misunderstanding the problem here. Can you re-explain? Or make [a sandbox](https://github.com/erikras/redux-form#-code-sandboxes-) to demonstrate it?

**Comment by mereskin** [comment]
@erikras maybe that's only when `parse`/`format` is specified? https://github.com/erikras/redux-form/issues/2768#issuecomment-298347572

I'll try to make a sandbox tonight.

**Comment by dariospadoni** [comment]
I'm also struggling with the same problem, I prepared a sandbox [here](https://codesandbox.io/s/n5z6jgJoP) which shows the issue I have.

In my case I have a select control whose values is a Object which I stringify and parse back to JSON in the field. The value of the form is first the selected one but then (on blur event) it gets reverted to the original value. Am I doing anything wrong? Are there any workaround?

**Comment by dmason30** [comment]
@erikras 
I have found this issue, I have a form that does some complex calculations onBlur that could dispatch a new value for the current field but after upgrading from 6.3.2 to 6.8.0 the onBlur is overwriting the value with the value of the field after I have done the calculations.

I have created a sandbox below which shows a simple onBlur that rounds the number to the nearest 10 and you can see that the number remains un rounded because of the CHANGE then BLUR. I have put a setTimeout also in to show that it correctly rounds the number afterwards.

Sandbox: https://codesandbox.io/s/l5XOknk05

**Comment by mlarcher** [comment]
Fwiw, it seems to me that a `onBlur={e => { e.preventDefault(); }` on the Field element brings us the expected behaviour with no downside. Gotta confirm there is no edge case though.

**Comment by martinbliss** [comment]
@mlarcher is correct. Passing a NoOp function to `onBlur` on the `Field` node works. If you use custom field inputs often, you can actually do this at your custom component level by "extracting" the `onBlur` event handler that is passed as part of `inputProps` and substituting it for your own that calls `e.preventDefault()`:

```
const CustomFieldInput = ({input: onBlur, ...inputProps}) => {
const handleBlur = e => e.preventDefault();
return <input onBlur={handleBlur} {...inputProps}/>; // note how `onBlur` from `Field` passed-in props is not being passed in here.
};
```

**Comment by nealoke** [comment]
I fixed it another way namely and works fine 👍 

```
handleBlur(event, newValue, oldValue) {
	newValue !== oldValue ? input.onBlur(event) : input.onBlur();
}
```

**Comment by An6r** [comment]
@mlarcher Looks like the downside of using e.preventDefault() is clearly explained in the [documentation](https://redux-form.com/7.2.0/docs/api/field.md/#-code-onblur-event-newvalue-previousvalue-gt-void-code-optional-)

> If you call event.preventDefault(), the BLUR action will NOT be dispatched, and the value and focus state will not be updated in the Redux store.

Probably focus state is not important in your case, but still...

**Comment by vclav** [comment]
Same problem here, we are using [react-select](https://github.com/JedWatson/react-select) which has controled, non-input `<div>` under the hood and redux-forms's `onBlur` empties value of field. The problem is, that event's target is `<div>` so i does not contains `value` property. I have format/parse set on field and calling `onBlur()` without arguments empties field as well. Current workaround is override `onBlur` with `noop`, which does not set meta properties, but for my current logic, I don't need it.

**Comment by Yankovsky** [comment]
Any progress on this issue? I think it is a consumer's responsibility to call onChange whenever he wants. But I do understand that we don't want to introduce a breaking change. So what about this flag @erikras was talking about.

**Comment by Yankovsky** [comment]
For now I am just manually dispatching blur action
```
handleBlur = () => {
	const {
		input: {
			name,
			value,
		},
		meta: {
			form,
			dispatch,
		},
	} = this.props

	dispatch(blur(form, name, value, true))
}
```

[This is what happens when you call input.onBlur](https://github.com/erikras/redux-form/blob/2770fb3a107ff350aa91985d3d3dc722bd9ad5a2/src/ConnectedField.js#L169)

[And this is the blur action creator](https://redux-form.com/7.4.2/docs/api/actioncreators.md/#-code-blur-form-string-field-string-value-any-code-)

**Comment by ladjzero** [comment]
ant-design's InputNumber hits this problem. onChange handler of InputNumber is fed with a number value, however onBlur is fed with a raw FocusEvent dispatched from the HTMLInputElement underneath. 

onChange is called immediately before onBlur if the value is corrected by min-max validations. Maybe these two events occur in the same frame mentioned by @carlsverre , the value of InputNumber is always reverted by the raw value from FocusEvent unexpectedly.

**Comment by kaleem-elahi** [comment]
> Another workaround is to use the parse (and / or possibly normalize) prop of Field to force the type value of that the blur action sets into state.
> 
> In my case, redux-form was converting number values of my fields into strings, causing issues with custom react-numeric input fields. [Line 99 of ConnectedField](https://github.com/erikras/redux-form/blob/892f45b5325fa7274cb6f8f0e7b3ea617b960c29/src/ConnectedField.js#L99) calls onChangeValue which "normalises" the value of the field using a function passed into the parse or normalize prop of ConnectField. In the absence of these functions being specified, the value seems to default to a string.
> 
> For what's worth, this is all I passed into the parse prop:
> 
> ```
> <Field
>   ...
>   parse={(value) => (parseInt(value, 10))}
>   ...
>   /> 
> ```
> 
> For it's worth, I agree with OP that the value being changed on a blur event is an unexpected and unconventional side effect that should considered for removal unless there's a really good reason for it.

also change input type to number.

**Comment by johnnybigoode** [comment]
> Using event.preventDefault() was not working for me, since input.touched was then not set to true (this is needed in my case for displaying input error hints). I think this is related to what @An6r mentioned above. It's not pretty, but I ended up passing down a callback that invokes input.onBlur without the event (this also satisfies my TypeScript compilation). If anyone has a better solution I'd love to hear it.
> 
> ```
> const renderChipInput: SFC<MergedProps> = ({
>   input,
>   meta: { error, touched },
>   ...rest,
> }) => {
>   const value = input.value || List()
> 
>   const onRequestAdd = (chip: any): void => {
>     if (invalidChip(chip)) { return }
>     input.onChange(input.value.push(chip))
>   }
>   const onRequestDelete = (chip: any): void => {
>     if (value.indexOf(chip) !== -1) {
>       input.onChange(input.value.delete(index))
>     }
>   }
> 
>   return (
>       <ChipInput
>         value={value}
>         onRequestAdd={onRequestAdd}
>         onRequestDelete={onRequestDelete}
>         helperText={touched && error}
>         onBlur={e => input.onBlur(undefined)}
>         {...rest}
>       />
>   )
> }
> 
> const FormChipInput: SFC<BaseFieldProps<MergedComponentProps> & FormChipInputProps> =
>   ({ name, componentProps, ...rest }) => {
>     return (
>       <Field
>         name={String(name)}
>         component={renderChipInput}
>         props={componentProps}
>         {...rest}
>       />
>     )
>   }
> ```
 I'm still having this issue. 
´onBlur={e => input.onBlur(undefined)}´
Solved

"redux-form": "^7.0.4",

**Comment by yunusunver** [comment]
> Using event.preventDefault() was not working for me, since input.touched was then not set to true (this is needed in my case for displaying input error hints). I think this is related to what @An6r mentioned above. It's not pretty, but I ended up passing down a callback that invokes input.onBlur without the event (this also satisfies my TypeScript compilation). If anyone has a better solution I'd love to hear it.
> 
> ```
> const renderChipInput: SFC<MergedProps> = ({
>   input,
>   meta: { error, touched },
>   ...rest,
> }) => {
>   const value = input.value || List()
> 
>   const onRequestAdd = (chip: any): void => {
>     if (invalidChip(chip)) { return }
>     input.onChange(input.value.push(chip))
>   }
>   const onRequestDelete = (chip: any): void => {
>     if (value.indexOf(chip) !== -1) {
>       input.onChange(input.value.delete(index))
>     }
>   }
> 
>   return (
>       <ChipInput
>         value={value}
>         onRequestAdd={onRequestAdd}
>         onRequestDelete={onRequestDelete}
>         helperText={touched && error}
>         onBlur={e => input.onBlur(undefined)}
>         {...rest}
>       />
>   )
> }
> 
> const FormChipInput: SFC<BaseFieldProps<MergedComponentProps> & FormChipInputProps> =
>   ({ name, componentProps, ...rest }) => {
>     return (
>       <Field
>         name={String(name)}
>         component={renderChipInput}
>         props={componentProps}
>         {...rest}
>       />
>     )
>   }
> ```

Thanks, worked for me 👍

**Comment by helight59** [comment]
> > Using event.preventDefault() was not working for me, since input.touched was then not set to true (this is needed in my case for displaying input error hints). I think this is related to what @An6r mentioned above. It's not pretty, but I ended up passing down a callback that invokes input.onBlur without the event (this also satisfies my TypeScript compilation). If anyone has a better solution I'd love to hear it.
> > ```
> > const renderChipInput: SFC<MergedProps> = ({
> >   input,
> >   meta: { error, touched },
> >   ...rest,
> > }) => {
> >   const value = input.value || List()
> > 
> >   const onRequestAdd = (chip: any): void => {
> >     if (invalidChip(chip)) { return }
> >     input.onChange(input.value.push(chip))
> >   }
> >   const onRequestDelete = (chip: any): void => {
> >     if (value.indexOf(chip) !== -1) {
> >       input.onChange(input.value.delete(index))
> >     }
> >   }
> > 
> >   return (
> >       <ChipInput
> >         value={value}
> >         onRequestAdd={onRequestAdd}
> >         onRequestDelete={onRequestDelete}
> >         helperText={touched && error}
> >         onBlur={e => input.onBlur(undefined)}
> >         {...rest}
> >       />
> >   )
> > }
> > 
> > const FormChipInput: SFC<BaseFieldProps<MergedComponentProps> & FormChipInputProps> =
> >   ({ name, componentProps, ...rest }) => {
> >     return (
> >       <Field
> >         name={String(name)}
> >         component={renderChipInput}
> >         props={componentProps}
> >         {...rest}
> >       />
> >     )
> >   }
> > ```
> 
> I'm still having this issue.
> ´onBlur={e => input.onBlur(undefined)}´
> Solved
> 
> "redux-form": "^7.0.4",

this action broke "asyncBlurFields"(

**Comment by helight59** [comment]
`onBlur={() => {}}`
this solution help me. Don't know why. AsyncValidate work fine

**Comment by R0kkusu** [comment]
I had the same issue with onblur and onfocusout, it change the input value to 'true' for some reason.
I worked around it by declairing a const that takes the current input value , and at the end of the code i set the input value to the previous const so it looks like nothing changed.
for example:
`const p = document.createElement("p");
function validate_fullname() {
    const keepvalue = fullname.value;
    if ( fullname.value = "" || fullname.value.length < 4) {
        p.innerHTML = "fullname invalid";
        fullname.after(p);
        fullname.value = keepvalue;
    }else {
        p.remove();
        fullname.value = keepvalue;
    }
}`
