### ISSUE TITLE
Field validate function should receive field props

### ISSUE THREAD

**Issue by ncphillips** [erikras/redux-form#2881]
### Are you submitting a **bug report** or a **feature request**?

Feature Request

### What is the current behavior?

Signature is:

```javascript
function validate(props, allValues, formProps)
```

### What is the expected behavior?

```javascript
function validate(props, allValues, formProps, fieldProps)


### Other information
<!-- Include here any detailed explanation, stacktraces, related issues, links for Stack Overflow, Twitter, etc. -->
I have a setup where the validate definition is decoupled from the props. I want to be able to change the validation at runtime based on config variables in the props. This needs to be done on a per-field basis.

**Comment by bradywatkinson** [comment]
Just wondering what the latest on this proposal is. It seems to me that a more robust pattern (at least what I personally have implemented) is to have the fields responsible for their own validation rather than the form. That being the case, having access to their own state will provide greater granular control

**Comment by conor909** [comment]
@erikras There seems to be some growing interest in this, do you have any thoughts around it?

**Comment by ncphillips** [comment]
@bradywatkinson how are you picturing implementing validation in the WrappedField?

**Comment by danielrob** [comment]
This is definitely desirable, PR's welcome.

**Comment by dfagan2** [comment]
I'm shocked that this isn't already baked in. I just combed through all the issues, but didn't even see a roundabout hack - is there one? I just want to know if a particular field is dirty as part of validation (for a use case where it has an initialValue set, but I want to ensure the final submitted value was explicitly set by the user, regardless of it is the same as the initialValue or not)

**Comment by danielrob** [comment]
As #4016 points out, one precedence this might create is that validation will run on any props change, so we need to tread carefully in that regard.

**Comment by danielrob** [comment]
@dfagan2 because you can't currently put props based validation logic 'underneath' the `Field` - in it's validation function, it presently must go 'above'. This is done by dynamically changing a validation function (or one in an array) passed to the `validate` prop during a render which will re-run (fixed in 7.4.2) the validation with that new function immediately. 7.4.2 will fail fast with an infinite loop if you don't manage this carefully (i.e. don't naively create a new `validate` prop on every render). I'm trying (being the keyword) to round the 'above' the Field approaches / patterns in #4017 in lieux of / as well as this being implemented.

**Comment by dfagan2** [comment]
@danielrob - Ok. Is there a way to extract field level meta props like dirty and pristine "above" the `Field`? I didn't see a Redux-Form method or selector at that level that could achieve that...

**Comment by conor909** [comment]
To be honest since working with redux-form a little longer I'v managed to do everything I needed to do without this feature.  It was strange at first because I expected the props to be there, but since diving into the api and using the action creators, and my own stateful component where my form lives I'v managed to do everything I wanted

**Comment by dfagan2** [comment]
@conor909 - care to share your wisdom? I'm still not sure how to accomplish field level dirty/pristine detection during validation (without this proposal)

**Comment by conor909** [comment]
@dfagan2  I was trying to achieve something different, but I just thought I'd share my experience.

**Comment by danielrob** [comment]
@dfagan2 it's been a while since I've done a personal round up of the latest in this area, but:
 - start with [getFormMeta](https://redux-form.com/7.0.3/docs/api/selectors.md/#-code-getformmeta-formname-string-code-returns-code-state-gt-formmeta-object-code-), it's had more and more added to it over time. 
 - Move on to this (in this context apologetically chatty) discussion about this question over time at #3289
 - If all else fails, somewhere floating around there's @erikras's comment pointing out there's nothing stopping you using `Field` as a meta selector. e.g. have a `Field` with a component that renders a `Field`. It does feel ugly, but it is just calling connect() at the end of the day which is what the selectors do anyway.
