### ISSUE TITLE
FieldArray removing property names if value is empty on blur (added after initialization)

### ISSUE THREAD

**Issue by Olliebaba** [erikras/redux-form#3366]
### Are you submitting a **bug report** or a **feature request**?

Bug Report

### What is the current behavior?

When an object is pushed to a field array, it can have properties with values defined in advance. (In the example below, note 'bob' as a pre-defined `firstName` when adding a member. However, when a property's value is an empty string blurring the corresponding input field causes the the form values to drop the property name in question.

To reproduce:
- open link below
- open console
- add a member
- open fields array printed in console. has both firstName and lastName props in first object.
- blur lastName without changing the value
- open newly printed fields array in console, lastName property is missing.
This appears to happen in `@@redux-form/BLUR`.

### What is the expected behavior?
That the key/value persist in the object.

### Sandbox Link

[A reproduction of the issue.](https://codesandbox.io/s/myjp96vk8p)

### What's your environment?

react v15.4.1
redux v3.6.0
redux-form v6.3.2

**Comment by iamdey** [comment]
This issue affect the architecture of my app too.

But it is not only related to `FieldArray`, it is due to how the `blur` action [modify a value](https://github.com/erikras/redux-form/blob/ca00a778af5e2ca5079fc9cac153bd33dd1e313d/src/createReducer.js#L196-L197) in the reducer (same in [`change` reducer](https://github.com/erikras/redux-form/blob/ca00a778af5e2ca5079fc9cac153bd33dd1e313d/src/createReducer.js#L217-L218)).

So If I try to manually add `{ foo: { bar: '' } }` to form values and display the bar field only if `foo` exists, it will never work because `bar` then `foo` will be removed from form values.

To manually add a value we must use `autofill` action.

Finally I suppose the following things can fix the issue:

* do not `deleteInWithCleanUp` if `autofilled` is true
* apply autofill, for the `arrayInsert, arrayPush, arrayUnshift, arraySplice` actions

I'm pretty new to redux-form I don't know if it can bring side effects. Any idea contributors ?

**Comment by ms88privat** [comment]
Having the same problem. Maybe the `deleteInWithCleanUp` function should also compare to the `initialValues` before trying to do the cleanUp`. This means, when we explicitly set the initialValues with a given structure, it should not delete it by default.

**Comment by erikras** [comment]
The equivalence of `''` and `undefined` in forms is a constant source of headaches.

The "Never Filled Out" and "Left Empty" cases need to be equivalent when calculating pristine/dirty. Is there some reason that you absolutely need `lastName` to not vanish in the example? Might it be easier to have your app understand that there is a `lastName` field on your form whether or not the JSON contains one?

**Comment by iamdey** [comment]
easier ? it depends on the feature/application architecture.

(If I remember well, [because I just disabled it](https://github.com/CaliOpen/Caliopen/blob/master/src/frontend/web_application/src/scenes/Contact/components/AddFormFieldForm/presenter.jsx#L42))
I have a Select which let the user to add a field. 
Since this field is in a sub property of formValues: `formValues.info.birthday` , the freshly added field just disappear if the user click outside (it's still usable but a UX nightmare).

So yes, In my case, I can duplicate the state of the form but with two source of trust it becomes no more maintainable.

--- 

@erikras thank you for making this great but complex library OSS. Keep the good work. I whish I can help more.

**Comment by bbenezech** [comment]
@erikras Can you start thinking of a v8 with a definitive solution ?

I would love 
- all empty values to be null : mandatory defaults, simply blowing up if key or value of field is missing
- no false
- no true (for booleans, use the value of the checkbox when checked, null if unchecked)
- no undefined (to cumbersome with key not present being the same as value being undefined, and the React controlled/uncontrolled input switch)
- no empty ""
- no empty {} (as it means it failed to have keys defined correctly recursively).

This would be a breaking change, but I can't state enough how huge this would be for the dirty tracking, the cleanliness of implementation and model.

There are so many issues today with falsy values I just sometimes want to rage-quit.

Plus the checkbox `undefined => true <=> false` is a design mistake : HTML only allows value present, value absent, plus ReduxForm does `undefined <=> non-empty-value` or `"" <=> non-empty-value` with strings, which is inconsistent with checkboxes.

**Comment by ms88privat** [comment]
Yeah, I think its time for v8 ^^

We are also using this format function as default for our fields: `const format = (value) => value == null ? null : value;`

**Comment by Olliebaba** [comment]
@erikras - Any status update on this issue?

**Comment by UlyssesInvictus** [comment]
This is a problem for me as well, but I just resorted to managing the actual desired behavior through state rather than using the current values in the store. IMO, the only annoying part of the current implementation is that onBlur unexpectedly manipulates values, not necessarily that empty/blank values in the store are treated the same as unset ones.

**Comment by ms88privat** [comment]
@UlyssesInvictus Looks like my PR got merged, it should work with a version where this one is included: https://github.com/erikras/redux-form/pull/3619

**Comment by StoikovOleh** [comment]
I just add to an input in the FieldArray: value={props.input.value || ' '}
 because I have field id in it, I know that it's not good style but it's work

**Comment by erikras** [comment]
Fix released in [`v7.4.0`](https://github.com/erikras/redux-form/releases/tag/v7.4.0).

**Comment by StoikovOleh** [comment]
thanks))


2018-06-12 11:27 GMT+03:00 Erik Rasmussen <notifications@github.com>:

**Comment by jpdesigndev** [comment]
I was seeing this issue as well, so I installed `[v7.4.0](https://github.com/erikras/redux-form/releases/tag/v7.4.0)`, but something appears to be very wrong.. Forms seem to be lazily added to the store (after focus for example) leading to very bad problems for my app. I will try to be more specific, but, for now, this is all I've gathered.

**Comment by mcupito** [comment]
I upgraded to 7.4.0 but am still experiencing this exact behavior. Is there a flag that needs to be set somewhere or something?
