### ISSUE TITLE
Initializing non-String form values with `initialize` action creator

### ISSUE THREAD

**Issue by damassi** [erikras/redux-form#365]
After upgrading redux form from 3.0 to the latest, i noticed that a good amount of my more complex form fields that aren't strings stopped working when going to edit (like react select, plus a few custom input widgets I've developed). I think that the issue is related to this:

<img width="1159" alt="screen shot 2015-12-01 at 1 20 45 pm" src="https://cloud.githubusercontent.com/assets/236943/11514678/9edef868-982e-11e5-897d-5f342122e6d3.png">

...with the `should only contain String values` requirement now being enforced in `3.1.x`, where before it wasn't. When I rolled back to `3.0.0` everything works fine. 

Curious as to why there is this limitation? A lot of form data isn't string based, and additionally, there is normalization / serialization requirements for managing different input data structures. For example, I have a few react select components that expect an array of objects that are different from my server requirements. I have to serialize these when i make updates and then deserialize when I load a page to edit. When translating back and re-populating within redux-form, the initial values need to be 

```
[
  {
    label: 'some label',
    value: 'some value'
  }
]
```

which isn't a string, and so the component never gets populated. In my higher order form library that I wrote around redux-form, i'm initializing these values via 

```dispatch(initialize(formName, deserialize(values))```

which performs the sync between the server and my form. To test that the String limitation is indeed the case, if I update my react select related form prop in `deserialize(values)` to a simple string, the component updates properly, per the documentation. 

Lastly, here's a screenshot of `3.0.0` `fields.fieldName.value`, just after `initialize` was dispatched. See how it populates any kind of data?

<img width="491" alt="screen shot 2015-12-01 at 1 57 32 pm" src="https://cloud.githubusercontent.com/assets/236943/11515633/b600d9da-9833-11e5-9754-46d04218350f.png">

Works as expected, where in the latest version `vendor` returns `undefined`.

Any help would be appreciated in understanding why you chose this design and / or idiomatic workarounds. Thanks so much

**Comment by erikras** [comment]
Yes, as of `v3.1`, it _should_ allow any kind of deep data, not just strings. The docs were out of date.

I'm not understanding the bug report here. It might be related to known issue #360, with array values.

I apologize for not understanding, but if you could give specific "When I do X, I get Y, but I expected Z" example, that might help.

**Comment by damassi** [comment]
@erikras apologies, I thought I was being clear. (And yes, I think it may be related to #360) 

More tersely: 

"When dispatching redux-form's `initializing` action creator with initial values that have key values that are not strings, those values will be undefined when reading via `this.props.values.field` or `this.props.fields.field.value`." 

This behavior did not happen in 3.0 - 3.0.12, but now happens in 3.1+. I'm asking why you chose to limit the types to just strings, per the image I posted above from the docs, which you have updated. (Could you provide a brief example of using the initialize action creator with deep values just so there is no confusion?) 

```javascript
import { initialize } from 'redux-form'

// Good, since key values are strings
class App extends Component {
  componentDidMount() {
    const initialFormData = {
      name: 'Chris',
      description: 'Developer',
    }

    this.props.dispatch(initialize('appForm', initialFormData))
  }
}

// Bad in 3.1+ since key values contain types that are NOT strings
class App extends Component {
  componentDidMount() {
    const initialFormData = {
      addresses: [
        {
          label: 'Home'
          value: '111 Something Street'
        },
      ]
    }

    this.props.dispatch(initialize('appForm', initialFormData))
  }
}
```

**Comment by erikras** [comment]
^^ The test I just added passes. Is it not the equivalent of your example?

**Comment by motoedie** [comment]
When I provide object
```javascript
const initialData = {
  application: {
    value: 13,
    label: 'some label'
  }
}
```
redux-form returns data for application:
```javascript
{initial: 13, value: 13}
```
When I provide array of these objects, result is `undefined`
```javascript
const initialData = {
  ctfs: [{
    value: 13,
    label: 'some label'
  }]
}
```

**Comment by damassi** [comment]
Later on today I'll provide an example project to illustrate

**Comment by erikras** [comment]
This should be fixed in [`v4.0.0`](https://github.com/erikras/redux-form/releases/tag/v4.0.0). Come and get it!

**Comment by damassi** [comment]
Awesome, thanks so much!

**Comment by tondapup** [comment]
@erikras dispatch(initialize(formName, deserialize(values)) ... will this re-render the component also ?

**Comment by sksahil030** [comment]
@erikras dispatch(initialize(formName, deserialize(values)) ... will this re-render the component also ?

**Comment by gustavohenke** [comment]
@sksahil030,
1. This issue was for the old v3.
2. Even if you're using it, why don't you try it, instead of asking?
3. If whatever you're trying to do still doesn't work even in latest versions of Redux Form, I recommend you to open a new issue instead of asking here.
