### ISSUE TITLE
Submit validation not working anymore ?

### ISSUE THREAD

**Issue by yleclanche** [erikras/redux-form#446]
Hello,

The submit validation example page (http://erikras.github.io/redux-form/#/examples/submit-validation) doesn't seems to work anymore.
On my local dev, I get "Uncaught (in promise) TypeError: Cannot read property 'submitError' of null" when I submit my form.
Not sure if It's related though.

**Comment by hnordt** [comment]
Same error here, even the API returns 200 OK and promise is resolved.

**Comment by hnordt** [comment]
Looks like the commit that introduced this bug is ee7a64f20a39bd147c80623d2dd0e682827f39dc

**Comment by VinSpee** [comment]
Also experiencing this issue. Getting a touch  but no validation :-(

**Comment by hnordt** [comment]
@VinSpee use `v4.0.1` for now. It's working.

**Comment by box-turtle** [comment]
I get same error in both 4.0.1 and 4.0.3 - "Uncaught (in promise) TypeError: Cannot read property 'submitError' of null"

**Comment by erikras** [comment]
Thanks guys. :+1: I will investigate. :mag:

**Comment by erikthedeveloper** [comment]
Ahhh thanks so much @hnordt I just spent 2+ hours wrestling this (new to `redux-form` and trying to dive straight into server side validation and hitting a wall with this error) and I was beginning to think I was just crazy. Downgraded my version to `v4.0.1` and now it is working exactly as expected :+1: 

Lesson learned: Consult GitHub Issues **before** Google. Thanks!

**Comment by box-turtle** [comment]
I believe the issue is the dreaded "null is an object" javascript quirk. 

If I change line 11 of setErrors.js  in v4.0.3 from 

```    if (typeof state === 'object') {  ```

to 

```    if (state && typeof state === 'object') {  ```

then the error goes away for me and validation works as expected. Not sure if that's the best way to do the null check because I'm not sure I fully understand the recursion logic that's going on here.

**Comment by erikras** [comment]
Excellent catch, @box-turtle! I've been bitten by that quirk more than once.

**Comment by erikras** [comment]
What puzzles me is how [these tests](https://github.com/erikras/redux-form/blob/master/src/__tests__/createReduxForm.spec.js#L852-L925) are passing, even with this broken.

**Comment by morgante** [comment]
@erikras It doesn't look like those tests actually check about asynchronous validation on form submission?

**Comment by erikras** [comment]
Fixed published. Problem in example was (at least partially) an actual bug in the example.

**Comment by morgante** [comment]
@erikras I'm not sure if this push caused it, but the docs aren't loading now: http://erikras.github.io/redux-form/

```store.js:9 Uncaught Error: Cannot find module "redux-form"```

**Comment by erikras** [comment]
Idiot error on my part. Thanks.

Apparently it helps to run `npm install` when you upgrade your library version. Who knew!? :see_no_evil:

**Comment by yleclanche** [comment]
Thanks erikras, but I still have the issue :  `Uncaught (in promise) TypeError: Cannot read property 'submitError' of null` when I submit my form and there are no errors.

In line 23 of setErrors.js.

If I replace :
`if (state[destKey]) {`

with
`if (state && state[destKey]) {`


It seems to work but not sure why state is null here.

**Comment by erikras** [comment]
@yleclanche Try v4.0.5.

**Comment by yleclanche** [comment]
Yep, 4.0.5 fixes it, thanks !
