### ISSUE TITLE
Setting initialValues causes two renders, messing up server sider rendering sometimes

### ISSUE THREAD

**Issue by adailey14** [erikras/redux-form#514]
I find when I pass initialValues as props to a reduxForm, the form renders twice. On the first render the form has almost everything setup except for the value properties of each field. It does have initialValue and defaultValue already present on the first render using the initialValues passed in, it is just missing the value property.

As a result, I found when I render this server side as in react-redux-universal-hot-example the server is rendering the first version (missing values) while the client is completing the twice-rendered version, which leads to a React checksum error like this:

```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) 1.0"><input value="$4,000" class="text-i
 (server) 1.0"><input value="$0" class="text-input
```

**Comment by erikras** [comment]
Not sure if related, but title sound suspiciously similar to #485. Will investigate later. :mag:

**Comment by adailey14** [comment]
Yep that definitely looks related. Here is a simple gist:
https://gist.github.com/adailey14/24d080b3b93c46740ab2

When I mount the SimpleFormConsumer component in my app and click to toggle the form, I see this in my console, showing the two renders:

```
RENDERING SIMPLE FORM, is Value set? undefined
RENDERING SIMPLE FORM, is Value set? Andrew
```

**Comment by sars** [comment]
Same problem for me...

**Comment by erikras** [comment]
This is a known bug, explained here: https://github.com/erikras/redux-form/issues/621#issuecomment-181898392

**Comment by andrewmclagan** [comment]
Also experiencing this as of [4.2.0]

**Comment by ooflorent** [comment]
Fixed in v5.1.4 (#843)

**Comment by ericluwj** [comment]
I am facing this issue in v7.0.5.
How can it be fixed?

**Comment by ninhxuanluu** [comment]
I am facing this issue too in v6.7.0. :(

**Comment by IRT-fbachmann** [comment]
Me either, version 7.0.3 :/
Any ideas for a quick and dirty fix?

**Comment by gustavohenke** [comment]
@ericluwj @IRT-fbachmann please open a new issue thoroughly demonstrating your problem 

@ninhxuanluu please try with newer versions of redux-form and, in case you still can't fix it, please follow the same path as the other folks.

**Comment by sandwichsudo** [comment]
@gustavohenke - I think the https://github.com/erikras/redux-form/issues/3570 demonstrates this issue with the latest version - any chance you could take a look please?
