### ISSUE TITLE
Slow with huge form

### ISSUE THREAD

**Issue by luisrudge** [erikras/redux-form#529]
Hi! I'm having some perf issues with a huge form I'm dealing with. 
The form has 83 fields (yeah.. I know.. but it is what it is) and typing on any input is impossible, as the input lags/hangs to the point where it becomes unusable.
For each key pressed, my component is rerendering. Is that the correct behavior?

I tested with the redux-form demo website and it lags as well if you add enough fields to it:

![mwwgfj1](https://cloud.githubusercontent.com/assets/941075/12243471/dc57edb8-b885-11e5-81fe-4c8f5fdaed39.gif)

See how the text appear in blocks of text, instead of one key after another. I captured this with 24fps, so it's not a gif issue.

**Comment by kristian-puccio** [comment]
Have you tried this in production mode with the dev tools turned off?

**Comment by kristian-puccio** [comment]
Also have you added pureRenderMixin to all the inputs?

I seperate each input into it's own component and make sure I use
pureRenderMixin so only the component that is changing gets updated

**Comment by luisrudge** [comment]
It lags in prod mode too (without devtools or redux-logger).

**Comment by luisrudge** [comment]
I'm not using pureRenderMixin though. I'll try that and let you know.

**Comment by erikras** [comment]
I did my best to only change the field objects that change with each action, but if I've messed up, all the fields might be trying to rerender or something like that. Some printouts should tell you. If that's the case, it's a redux-form bug. #375 suggests that it is.

**Comment by luisrudge** [comment]
Yeah.. Even implementing a custom shouldComponentUpdate, it still lags really hard. :(

```js
shouldComponentUpdate(nextProps) {
  const currentProps = _.pick(this.props, 'defaultValue', 'initialValue', 'valid', 'active', 'touched', 'value');
  const otherProps = _.pick(nextProps, 'defaultValue', 'initialValue', 'valid', 'active', 'touched', 'value');
  return !_.isEqual(currentProps, otherProps);
}
```

So, the thing is.. All my inputs are re-rendering even when you focus/blur on any input.. Is #375 related to that?

**Comment by luisrudge** [comment]
@erikras @kristian-puccio do you guys have any idea how I can mitigate that for the time being?

**Comment by kristian-puccio** [comment]
you could always try to debounce the onChange event through the lodash
debounce. But then you'll have to track the state locally so you can see
the updates as you type.

There was someone else doing the same thing in the issues
https://github.com/erikras/redux-form/issues/454

**Comment by erikras** [comment]
This issue, and others, like #544, is making me reconsider whether or not to use ImmutableJS internally. The complexity of maintaining nested object instances is quite difficult, and all that would go away with ImmutableJS.

**Comment by luisrudge** [comment]
@erikras that sounds like lots of effort though.. are you sure it will solve this issue?

**Comment by damassi** [comment]
Immutable persistent data structures FTW. I think it would simplify a lot of tasks going forward once the initial scaffolding is in place

**Comment by kristian-puccio** [comment]
Be interesting how you choose to integrate it if you do.

Peer Dependancy or Dependancy.

Do you iterate with the api via the immutable api? I use immutable already
so for me it would be a great change but for someone who doesn't?

But then I sort of feel like redux-form is quite a sophisticated project
not the sort of thing your going to pickup as a beginner as you have to
know react + then also redux before you even start.
So if the project is aimed at developers with that level of experience
already then immutable.js isn't a hard thing to grasp and quite likely to
be in use already.

**Comment by erikras** [comment]
In addition to some sanity-checking tests (see commits above), I have looked into the ImmutableJS idea.

I don't see that much benefit to it, since I will still have to do all the tree-traversal (via field strings) I'm already doing, and I'm already sharing as much memory (not deep copying) as possible, via the `...` spread operator.

And adding a dependency would be a big deal, not to mention that it would require users of the library to take the ImmutableJS state into account when serializing and deserializing the store.

I think I've talked myself out of it for now. Arguments in either direction are welcome.

**Comment by erikras** [comment]
@luisrudge Does the `debounce` suggestion help?

Another thing you could try is removing the `onChange` and only updating the redux store `onBlur`. Like this: https://github.com/erikras/redux-form/issues/293#issuecomment-157738158

**Comment by wmertens** [comment]
I think some profiling would be good, perhaps something in the component is
causing the issue…

On Sun, Jan 17, 2016, 10:00 AM Erik Rasmussen <notifications@github.com>
wrote:

> @luisrudge <https://github.com/luisrudge> Does the debounce suggestion
> help?
>
> Another thing you could try is removing the onChange and only updating
> the redux store onBlur. Like this: #293 (comment)
> <https://github.com/erikras/redux-form/issues/293#issuecomment-157738158>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/erikras/redux-form/issues/529#issuecomment-172302594>.
>
-- 

Wout.
(typed on mobile, excuse terseness)

**Comment by steida** [comment]
onBlur, caching, immutable.js, I suppose nothing can help for huge forms, or will be half broken, and definitely will be pita for debugging. Imagine long list of editable items, we have two options.

1) connect every item form with data, basically use observer pattern
Every hoc must use observer pattern. And what if we want to read values else where? Use form hoc as well?

2) pass everything through props and leverage pure components

I am using immutable js and pure components in https://github.com/este/este a lot, and I always ended with custom forms implementation, which sucks ofc, but nothing else helped for everything editable apps. Maybe it's time to revisit redux-form pattern.

**Comment by wmertens** [comment]
Like I said, profile. The whole React app uses the same principle and is
not slow so likely there are good opportunities for optimization.

On Sun, Jan 17, 2016, 5:03 PM Daniel Steigerwald <notifications@github.com>
wrote:

> onBlur, caching, immutable.js, I suppose nothing can help for huge forms,
> or will be half broken, and definitely will be pita for debugging. Imagine
> long list of editable items, we have two options.
>
> 1) connect every item form with data, basically use observer pattern
> Every hoc must use observer pattern. And what if we want to read values
> else where? Use form hoc as well?
>
> 2) pass everything through props and leverage pure components
>
> I am using immutable js and pure components in
> https://github.com/este/este a lot, and I always ended with custom forms
> implementation, which sucks ofc, but nothing else helped for everything
> editable apps. Maybe it's time to revisit redux-form pattern.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/erikras/redux-form/issues/529#issuecomment-172344839>.
>
-- 

Wout.
(typed on mobile, excuse terseness)

**Comment by erikras** [comment]
@steida The "what if every input was connected to only its slice of the redux store?" idea crossed my mind. I presume that's what you mean by your first option. Seems messy as hell.

Everything through props is sort of how it's done already...

@wmertens By profiling, do you mean in Chrome devtools, or is there a better tool?

**Comment by wmertens** [comment]
Devtools and react perf

On Sun, Jan 17, 2016, 6:05 PM Erik Rasmussen <notifications@github.com>
wrote:

> @steida <https://github.com/steida> The "what if every input was
> connected to only its slice of the redux store?" idea crossed my mind. I
> presume that's what you mean by your first option. Seems messy as hell.
>
> Everything through props is sort of how it's done already...
>
> @wmertens <https://github.com/wmertens> By profiling, do you mean in
> Chrome devtools, or is there a better tool?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/erikras/redux-form/issues/529#issuecomment-172353716>.
>
-- 

Wout.
(typed on mobile, excuse terseness)

**Comment by erikras** [comment]
I'm having trouble getting my head around the Chrome perf tools. Anyone willing to post a graph or readout of what happens when the pound on the keyboard like the screenshot above would be appreciated.

@wmertens Wout, stop replying by email! :rage: :stuck_out_tongue:

**Comment by luisrudge** [comment]
I can do that!

**Comment by erikras** [comment]
I looked up @luisrudge on Wikipedia, but it forwarded me to [this page](https://en.wikipedia.org/wiki/Infinite_monkey_theorem).

:stuck_out_tongue: :heart: :smile:

**Comment by luisrudge** [comment]
damn.. :thought_balloon:

**Comment by erikras** [comment]
:guitar: Rock on, LR!

**Comment by steida** [comment]
@erikras I like your avatar. Same here .)

**Comment by luisrudge** [comment]
![image](https://cloud.githubusercontent.com/assets/941075/12379992/3a5fccb0-bd4e-11e5-84df-b990cc09b58e.png)

First event is focus, second one is keypress.

**Comment by erikras** [comment]
Okay, and what does that tell us?

It might be too much to ask, but I'd love a declaration of "It spends 80% of the time in X subroutine" conclusion.

**Comment by steida** [comment]
I'm just in the middle of thinking whether I should help to fix redux-form, or just create something else. Plain Redux approach means a lot of verbose boilerplate, but fighting with redux-form is even worse for me. Very sorry to say that, redux-form awesome, but it seem it's too big abstraction.

**Comment by luisrudge** [comment]
ahh, sorry. I didn't know you wanted some kind of analysis on this.. I just know how to collect them :( I'm uploading the timeline's json file

**Comment by luisrudge** [comment]
PLease download my timeline json from here: https://onedrive.live.com/redir?resid=F839C2B07BCC1AAF!409484&authkey=!AETkMzGWKUfOIMk&ithint=file%2cjson

**Comment by luisrudge** [comment]
You can load this file inside chrome's "Timeline" tab

**Comment by luisrudge** [comment]
This is the timeline when writing a sentence: https://onedrive.live.com/redir?resid=F839C2B07BCC1AAF!409485&authkey=!ABbsE8KY1E1uAc4&ithint=file%2cjson

**Comment by erikras** [comment]
@steida To be honest, as the author of this library, I'm not 100% convinced that every-damn-keypress warrants a redux action. I asked @gaearon one day, and he said, "Sure, why not?", so I built it. I'm curious as to the details of "too big abstraction".

@luisrudge I loaded that file, but it's all React crap. Not seeing any redux-form "hotspots".

**Comment by luisrudge** [comment]
sure, well.. redux-form is triggering a render everytime, that's why it's slow.. :(

**Comment by erikras** [comment]
Render of _what_, exactly? See unit test commits above.

**Comment by steida** [comment]
@erikras We are both on the same boat. I will try to bring up better approach, or shut up ofc.

**Comment by luisrudge** [comment]
Every input in my page.. :( Maybe we 3 can go in a call so I can show what's actually happening? Maybe I'm just missing something

**Comment by luisrudge** [comment]
If I use `return this.props.field !== nextProps.field;` in my `shouldComponentUpdate`, my components don't update at all

**Comment by erikras** [comment]
@luisrudge That's very strange. Either your code is broken or [my test](https://github.com/erikras/redux-form/commit/5e69a8c33967f8c4e9d4d65dafd72b085166721a) is broken. I'd happily accept the latter, but I don't see how. Ideas?

**Comment by luisrudge** [comment]
@erikras sorry! I was wrong. I even deleted my comment short after posting it, after realizing I was doing something stupid :D

**Comment by erikras** [comment]
I added [React Perf](https://facebook.github.io/react/docs/perf.html) to the [Examples Repo](https://github.com/erikras/redux-form/tree/gh-pages).
```
npm install
npm run dev
```
If any of you want to test it out... I'm not really sure how to interpret the printouts.

**Comment by luisrudge** [comment]
I can add that to my code if someone knows how to interpret the printouts.

**Comment by trashgenerator** [comment]
As a workaround I'm currently suppressing onChange event and sending only onBlur
```
class Input extends React.Component {
  constructor(props) {
    super(props)
    this.state = {value: props.value};
  }

  componentWillReceiveProps(nextProps) {
    if (nextProps.value !== this.state.value) {
      this.setState({value: nextProps.value});
    }
  }

  onChange = (e) => {
    this.setState({value: e.target.value})
  }

  render() {
    const newProps = {
      ...this.props,
      onChange: this.onChange,
      value: this.state.value,
    }
    return (
      <input {...newProps}/>
    );
  }
}
```
Now it's much better. At least you can type. But anyway the whole form is very slow. For example when you select option in select field or when focusing text field.

I started experimenting with measuring speed on key press. Execution of all my reducers takes only 1-2 ms. But react part(rendering or whatever) can take 100-200ms on huge forms. Will continue to investigate. At least will try to use PureRenderMixin

**Comment by erikras** [comment]
Good data, @trashgenerator. It makes sense that the Redux part of it would be speedy, since it's just data structure manipulation. React likes to brag about "_OMG! It rerenders the whole page!!_", but 5-10 frames per second is pretty shitty. The only thing I can think of is that maybe form elements in the browser DOM are just generally slower to render (more listeners and crap?) than regular divs, for which React prides itself on silky smooth FPS.

**Comment by gaearon** [comment]
You need to use something like PureRenderMixin *at the very least* if you expect any kind of performance from React. I'm happy to take a look at perf problems if you can provide a particular repo reproducing them.

**Comment by luisrudge** [comment]
@gaearon nice! If you go to the redux-form's website (http://erikras.github.io/redux-form/#/examples/deep?_k=veahqz), it already starts slowing down when you add a bunch of fields. The examples are in this repo, I believe.
I added 10 children and 10 awards to one of the children. If you type very fast inside any input, you'll notice pretty quick the issue

**Comment by gaearon** [comment]
Are you

1) Disabling DevTools
2) Running a production build of React

when checking performance?

**Comment by erikras** [comment]
The answers are 1) no, and 2) yes, for that live demo link. I will make it possible to disable the redux devtools later today.

**Comment by erikras** [comment]
Okay, now if you go to [`http://erikras.github.io/redux-form/?noDevTools`](http://erikras.github.io/redux-form/?noDevTools), the DevTools will be disabled, and it will use production React.

It doesn't seem to lack much, except for when you press ten keys simultaneously, but then so does this input I'm typing in on GitHub, so...

**Comment by trashgenerator** [comment]
http://erikras.github.io/redux-form/?noDevTools#/examples/deep

try to add 30 children with 10 awards each.

**Comment by erikras** [comment]
@trashgenerator Yep, it gets sluggish. There are still optimizations that could be made with `shouldComponentUpdate`. I'll see what I can do.

**Comment by erikras** [comment]
I've done two things to the [Deep Form](http://erikras.github.io/redux-form/?noDevTools#/examples/deep):

1. Added a button to programmatically add 30 children and 10 awards each, as @trashgenerator suggested.
2. Created a [`PureInput`](https://github.com/erikras/redux-form/blob/gh-pages/src/components/PureInput.js) component that implements `shouldComponentUpdate` for max field efficiency.

Still slow when enormous.

@gaearon Any other ideas?

**Comment by kristian-puccio** [comment]
I'm really enjoying reading this, I have made quite a few of the mistakes
listed while using redux-form. the .bind creating a new function reference
being the most prominent one.

https://medium.com/@esamatti/react-js-pure-render-performance-anti-pattern-fb88c101332f#.nligrwe4d

**Comment by erikras** [comment]
Excellent link, @kristian-puccio. Someone, me if no one beats me to it, should look over the `redux-form` component code with an eye for function creation. I _feel_ like I've been extremely careful about that, but there may be some culpable code in there.

**Comment by jhabdas** [comment]
@trashgenerator your solution worked beautifully, and I'm not even using this module. kudos

**Comment by trashgenerator** [comment]
@jhabdas great! :)

**Comment by tomduncalf** [comment]
I too have encountered these performance issues, judicious use of `pureRenderMixin` or similar helped quite a lot but I was still encountering this bug where another form on the page would re-render every time the other one updated: https://github.com/erikras/redux-form/issues/432 (which was slow even with pureRender, due to time spent in the `ReduxFormConnector`), which I ended up working around by hiding the other form when the other was open (in a modal) :/ I don't work on that app any more thought so can't rule out that it was an error on my part.

I'm using `redux-form` in a new project now and will be keeping a close eye on performance, with a view to contribute back some fixes if I do come across problems!

For future reference for anyone who would like to profile their application using React perf tools, here is how I do it:

Pre-requisites: `npm install react-addons-perf` and then expose the `Perf` object on `window` (only in dev mode of course) - I do this like: 

```
import * as Perf from 'react-addons-perf' // Typescript style import, yours may differ

if (config.dev) {
  window['Perf'] = Perf
}
```

Then to use it:

1. When you want to start measuring, open the console and type `Perf.start()`
2. Perform the actions you want to profile (if you want to profile the initial load, you may need to put `Perf.start()` in the Root.tsx file or wherever instead, so it starts recording before the initial render)
3. `Perf.stop()`
4. `var results = Perf.getLastMeasurments()`
5. You can then use the print* methods described at https://facebook.github.io/react/docs/perf.html to analyse the performance of the React application, passing in the results variable from 4, e.g. `Perf.printWasted(results)` to print any components that wasted time re-rendering themselves with no difference to the resulting output (i.e. could be optimized with `shouldComponentUpdate`) and `Perf.printInclusive(results)` to print how much time is spent in each component (useful to track down ones which are slow to render)

**Comment by steida** [comment]
I made simple hackable redux-fields with similar but very limited API based on immutable.js and by my own tests, it's superfast. 

For inspiration:
https://github.com/este/este/tree/80b2207409fa86fba5dc24b54dcb1047654dabc7/src/common/lib/redux-fields

**Comment by davidkpiano** [comment]
@steida The [react-redux-form](https://github.io/davidkpiano/react-redux-form) library works on the same principle, using [https://github.com/aearly/icepick](https://github.com/aearly/icepick) instead of immutable.js for working with plain JS objects (and is very lightweight).

I think the key here is the **separation** of model state and form state, which allows the library to update the respective states in the reducers quickly without having to reconstruct the large hybrid form-model state (which is how redux-form works).

@erikras Would you think it would be worth the effort to separate model and form state in redux-form? I think a lot of the complexity and performance bottleneck lies in the combination and management of the two as a single state.

**Comment by steida** [comment]
@davidkpiano Check Este implementation. The form state is updated only when model has been changed. By my own experiences there is no performance bottleneck.

**Comment by jhabdas** [comment]
In building a non-trivial form with nested, conditional sub-form against
two related endpoints what got the job done for me was to create a
synchronous UI reducer to manage form state in memory and use it to spread
the form control names and values over my domain models prior to persisting
to the server. This required some clever flow control and schema validation
on the client but led to a stunning user experience nonetheless.

**Comment by luisrudge** [comment]
@jhabdas can you clarify that a bit please?

**Comment by jhabdas** [comment]
Would love to get into the nitty gritty, but what I'm suggesting is David
is onto something.

**Comment by erikras** [comment]
If @davidkpiano's theory is correct, that splitting the form and model state is the answer, then the bottleneck in `redux-form` would be [the `readFields()` call](https://github.com/erikras/redux-form/blob/master/src/createHigherOrderComponent.js#L50), which is where _all_ the logic for generating the `fields`, `values`, and `errors` props is. When I place timers around that line, even on the gigantic deep form example, I can never really get it over 15-25 ms. While that could be improved, and I think that separating model from form state would help, as well as provide additional benefits, I don't _think_ that's the major hotspot.

I _think_ the problem is related to the fact that the whole form component has to rerender any time any field changes. Even if each input is "pure" and doesn't rerender if its field data hasn't changed, that's still a potentially big tree for reconciliation. However, rerendering the whole form is not really something you can get around if you want to render anything involving form-wide `dirty` or `invalid` state.

The alternative is to connect little parts of your form, e.g. where you want to toggle something based on whole form state, via helper components, but then you get into horrible Angular-esque logic components, like:
```js
<div>
  FORM INPUTS HERE
  <IfValid>
    <button type="submit">Submit</button>
  </IfValid>
  <IfInvalid>
    <button type="submit" disabled={true}>Submit</button>
  </IfInvalid>
</div>
```
...along with wrapping each field with its own component like @davidkpiano has done.

My favorite part of the API of `redux-form` is the destructuring of the field objects into any input component (`<input {...firstName}/>`). That feels way more elegant than `<Field field="firstName"><input/></Field>` to me, especially since the latter involves cloning `children`. I like how `redux-form` doesn't have to provide a slew of specialized components.

Thinking outside the box here..... what if....

What if the HOC wasn't `connect`ed at all, but provided a useful set of props, some of which were components that only `connect` to the slice of store that they need.

```js
@reduxForm({
  form: 'crazyIdeaForm',
  fields: ['name', 'notes', 'favoriteColor']
})
class CrazyIdea extends Component {
  render() {
    const {fields: {name, notes, favoriteColor}, handleSubmit, submit} = this.props;
    return (
      <form onSubmit={handleSubmit}>
        <name.input placeholder="First Name"/>  // uses React.DOM.input
        <name.error showWhenTouched className="myCustomErrorClass"/>

        <notes.textarea placeholder="Notes"/>   // uses React.DOM.textarea
        <notes.error showWhenTouched className="myCustomErrorClass"/>

        <favoriteColor
          mapProps={({value, onChange}) => ({ color: value, onColorPicked: onChange })}>
          <CustomColorPickerComponent/>
          // expects value to be in "selected" prop and uses "onColorPicked" callback
          // rather than "onChange".
          // will have its props applied via cloning, like react-redux-form does
        </favoriteColor>

        <submit disableOnInvalid disableOnSubmitting>Submit</submit>
      </form>
    );
  }
}
```

Is that awesome or totally insane?

**Comment by davidkpiano** [comment]
> Is that awesome or totally insane?

A little insane but I love the direction you're going in :smile: 

I know that `<Field><input /></Field>` may not be the most elegant API, but it accomplishes the goal you state above - `connect()` _only_ the relevant parts of the form instead of the whole form, so rerendering happens almost exclusively at leaf nodes, essentially.

Ideally, something like `<input type="text" {...field('foo.bar')} />` would be the best of both worlds (especially if options can be passed in like: `field('foo.bar', { type: 'radio', validators: { ... }})` but the only issue with that is actually `connect()`ing each control without having to connect/decorate the entire form first.

Also, `<Field model="user.firstName"><input /></Field>` provides access to lifecycle methods for the controls, so optimizations can be made to when it should update, and by having a HOC on the control, states such as `checked` can immediately be inferred from the `model` value. The only downside, as you said, is that it's a custom prop mapping for each component (though this is somewhat of a benefit for DX).

So perhaps a good solution for Redux-Form would be to have a HOC that binds actions to the dispatcher and provides a single `field()` prop that adds the useful set of props you mentioned?

```js
@reduxForm({
  form: 'somewhatLessCrazyIdeaForm'
})
class SomeForm extends Component {
  render() {
    const { field, handleSubmit, ... } = this.props;

    return (
      <form onSubmit={ handleSubmit }>
        <input type="text" {...field('firstName')} />
        // etc.
      </form>
    )
}
```

**Comment by steida** [comment]
As I wrote I already implemented it https://github.com/este/este/tree/master/src/common/lib/redux-fields You can use it for redux-form redesign.

**Comment by erikras** [comment]
@davidkpiano, the `...field('foo.bar')` syntax was suggested eons ago (in javascript library time) by @yesmeck: https://github.com/erikras/redux-form/issues/55#issuecomment-150937333. You are right that it still fails to accomplish the "only `connect` leaves" goal, which is the main problem we're trying to solve. The "don't need to specify `fields` array upfront" benefit is secondary.

**Comment by wmertens** [comment]
How about `<Fields.foo.bar>{f => <input {...f}/>}</Fields>`? I think that would be feasible.

`Fields` would be passed by redux-form to the form component, and `Fields.foo.bar` would be subscribed individually to just `foo.bar`. The single child function gets the field element as before.

**Comment by erikras** [comment]
@wmertens Interesting compromise there. The "function of child as component" paradigm is a little disgusting, though, in my opinion. Your suggestion is similar to my `<favoriteColor mapProps>` syntax, but avoids the cloning yuckiness. I'm not sure which is more acceptable.

Excellent contribution to the discussion; it's an angle I had not considered.

**Comment by wmertens** [comment]
@erikras other option, probably better (I too dislike the function-as-a-child):
```
<Fields.foo.bar render={f =>
    <input {...f}/>
}/>
```
That even shaves off a `</Field>`…

**Comment by erikras** [comment]
Good thinking. :+1: :thought_balloon:

**Comment by davidkpiano** [comment]
@wmertens @erikras that's almost no different than:

```
<Field model="foo.bar" children={<input type="text" />} />
```

I think we're converging on the same idea, to be honest.

**Comment by wmertens** [comment]
@davidkpiano indeed, the thinking is very similar, it's just about little details, like avoiding having to clone the children of Field, and whether or not to define fields ahead of time.

**Comment by visortelle** [comment]
Is it possible to just add a little timeout ( ~50ms ) between onChange's to detect "stop typing" and update redux on typingStopped && old-new-value-length-diff > 5 chars.

**Comment by wmertens** [comment]
That would break expectations. However, you can do that yourself with a
wrapper component for the inputs…

> --

Wout.
(typed on mobile, excuse terseness)

**Comment by davidkpiano** [comment]
@erikras Sorry if someone pointed this out already, but I just realized that this pattern:

```js
<input type="text" {...fields.username} />
```

...even though it's terse and readable, incurs a ton of overhead on every `render()` by forcing the `fields.*` object to be cloned _every single time_, regardless of if any of the properties/methods on that object have changed (which, most of them never change). `Object.assign()` (or Babel's `_extend()` polyfill) ends up being called every time the entire form rerenders. That might be where the performance bottleneck is.

**Comment by gaearon** [comment]
AFAIK `<input type="text" {...fields.username} />` is not different from manually writing `<input type="text" a={fields.username.a} b={fields.username.b} c={fields.username.c} />` etc (assuming `a`, `b`, `c` are fields on `fields.username`.

Yes, it uses `Object.assign` but you’d still have to copy those properties to some object before passing it as props if you want additional props like `type`.

**Comment by erikras** [comment]
Excellent comments, @davidkpiano and @gaearon. Thanks.

**Comment by kristian-puccio** [comment]
One thing I've been thinking about with the possible HOC design is to work
out how people are displaying forms.

For me tend to have each input in a seperate react component so a function
that returns a HOC would be very handy here.

But maybe lot's of people inline an entire form inside one component so a
parent style HOC would be useful.

Probably easy to have the api support both I guess.

**Comment by gaearon** [comment]
By the way I encourage you folks to try https://github.com/omnidan/redux-ignore. It lets you skip some (or all) of *your* reducers when handling form actions.

**Comment by ffxsam** [comment]
I'm having key lag even on just a single `<TextField />` in Material UI. As soon as I remove redux-form from the equation, it's very responsive again.

**Comment by ffxsam** [comment]
Would simply making it not report `CHANGE` fix this? I'd fork it and change that myself, but honestly I'm having a difficult time tracing the code and figuring out where things happen.

**Comment by MitchWeiss** [comment]
Oh man, I'm starting to experience these performance issues as well. Wish I knew about this before I started :(

Separating each input into a separate component to use PureRenderMixin or ShallowCompare seems like a nightmare

**Comment by jhabdas** [comment]
You all saw Alexander's workaround, right? If it was plugging up my form,
personally, I'd monkey patch before forking or tempting fate of
maintainability with immutables.
On Wed, Mar 2, 2016 at 12:17 AM Mitchell Weiss <notifications@github.com>
wrote:

> Oh man, I'm starting to experience these performance issues as well. Wish
> I knew about this before I started :(
>
> Separating each input into a separate component to use PureRenderMixin or
> ShallowCompare seems like a nightmare
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/erikras/redux-form/issues/529#issuecomment-191084220>.
>
-- 
Josh Habdas
tel: +1 (630) 290-3542
web: http://habd.as

**Comment by kristian-puccio** [comment]
I think separating into components is the react way. Otherwise react has no
choice but to re-render everything if one bit of data changes.

I create base widgets that I pass options like name and type to, and of
course field.

Makes my code easier to read as a side benefit.

**Comment by epeli** [comment]
Would it be possible just to debounce `onChange` of the text input components? With some local state so that `value` would also work.

Is there a demo of slow performing form? I'm also considering using this lib but before that I'd like to take stab on the perf issues.

**Comment by leesiongchan** [comment]
+1 to immutable structure.

**Comment by davidkpiano** [comment]
@epeli Yes, to debounce onChange you just have to "decorate" the `onChange` method of the `field` object:

```js
import debounce from 'lodash/debounce';
// ...

// in render()...
const { fields } = this.props;

<input type="text" {...fields.email} onChange={debounce(fields.email.onChange, 1000)} />
```

@leesiongchan: Immutable structures would make a negligent amount of difference, I strongly believe (especially compared to internal, non-exposed mutation). They're more for data integrity than performance, to my understanding.

The sheer amount of updates that happen when a field is changed can be to blame - many parts of the form state are updated every time a field changes, regardless of if the developer even cares about those parts (such as `focus`, `touched`, `pristine`, etc.)

I still strongly believe that separating form and model state, making form state opt-in, as well as separating out into components such as `<Field ...><input type="text" /></Field>` for greater control over reconciliation like @kristian-puccio suggested is the way to go to achieve performance.

**Comment by tomduncalf** [comment]
I'm worried about hitting these performance issues again, I hit them on a previous app but that was a very complex form - I really like redux-form, but it's a potential show-stopper if this does happen again.

What was killing it for me was mostly the top level redux-form component re-rendering itself rather than individual form components IIRC (I already create individual form components with pureRender).

What's the accepted "solution" at the minute? Debounce `onChange` or something similar? Or some other form library? I'd really rather not change, there's a lot I love about redux-form!

**Comment by wmertens** [comment]
To get a feel for the situation, use react devtools in chrome/ff and turn
on painting on react updates. Then you can see that any value update
re-renders everything in the form.

The only way around it is an approach like <Fields.foo render={f => <input
{...f}/>}/> which could be made to subscribe to only updates to the "foo"
field.

On Wed, Mar 2, 2016 at 5:36 PM Tom Duncalf <notifications@github.com> wrote:

> I'm worried about hitting these performance issues again, I hit them on a
> previous app but that was a very complex form - I really like redux-form,
> but it's a potential show-stopper if this does happen again.
>
> What was killing it for me was mostly the top level redux-form component
> re-rendering itself rather than individual form components IIRC (I already
> create individual form components with pureRender).
>
> What's the accepted "solution" at the minute? Debounce onChange or
> something similar? Or some other form library? I'd really rather not
> change, there's a lot I love about redux-form!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/erikras/redux-form/issues/529#issuecomment-191317332>.
>
-- 

Wout.
(typed on mobile, excuse terseness)

**Comment by erikras** [comment]
All,

I am in the process of a fairly substantial rewrite for `v5`, primarily focused on performance, using many of the concepts from this discussion. It might be a couple more weeks before it's ready, but I hope, barring any unforeseen problems, to have a beta out to you guys in March. Please hang tight and, for the time being, either [debounce your `onChange`](https://github.com/erikras/redux-form/issues/529#issuecomment-191261190) or [remove it altogether](https://github.com/erikras/redux-form/issues/529#issuecomment-172653330). Putting "pure render" logic on your inputs will not be as effective, as the primary problem, I believe, is that the entire form is rerendering to provide your form component with props like `values`.

In the meantime, I think it might help if the `function` props were cached somehow. #544 It should not be [creating new functions on every render](https://github.com/erikras/redux-form/blob/master/src/createHigherOrderComponent.js#L126-L135). If one of you would like to look into that, I think it might help a lot.

Thank you for your patience and support of this library.

-Erik

**Comment by luisrudge** [comment]
@erikras :tada: you're awesome! Keep it up!

**Comment by luisrudge** [comment]
@erikras do you think the api will change much?

**Comment by erikras** [comment]
@luisrudge As little as possible...

**Comment by tomduncalf** [comment]
Great news @erikras, look forward to seeing the new version :) Thanks again for all your hard work!

**Comment by jcalfee** [comment]
Glad you have a fix.. In the spirit of brevity this work-around seems to work well for everything except for autocomplete fields..

In render:  
```javascript
window.reduxFormPerformFix(this.props.fields)
```
```javascript
window.reduxFormPerformFix = fields => {
    Object.keys(fields).forEach(el => {fields[el].onChange = e => {fields[el].value = e.target.value}})
}
```

**Comment by luisrudge** [comment]
@jcalfee can you explain why this would make things faster?

**Comment by erikras** [comment]
Hey guys. Just wanted to let you know [`v6.0.0-alpha` has been released](https://github.com/erikras/redux-form/releases/tag/v6.0.0-alpha.4)!

**Comment by jcalfee** [comment]
@luisrudge this was only a work-around for having slow renders...  DevTools was installed in our development env (not the plugin, the buggy npm package).  I later found this out using Perf.start(), stop, .... 

My work-around just mapped the onChange event back into the components value variable.  It was intended to prevent the frequent onChange events from firing actions.  It did speed things up but later I had issues (not sure why).  So, I just moved on and removed that work around.. We are fine running the released version and original API now..  I'll use Perf to spot any issues in the future.

**Comment by jcalfee** [comment]
About the alpha, doesn't the username => function get created on every render causing react to always think the DOM needs to be updated?
```js
<Field                                // wrap in Field
          name="username"                     // specify field name
          component={username =>    
```

**Comment by erikras** [comment]
@jcalfee Interesting observation! This is exactly the kind of feedback I was looking for.

Yes, it would get created on every form rerender, but the intent of the release is to minimize those. The form will only rerender if `valid`/`invalid` or `dirty`/`pristine` or the global error changes, which should be pretty rare.

Also, on most well structured apps, you will be using a reusable component, probably a stateless function`, for the `component` prop.

**Comment by wmertens** [comment]
@erikras that looks amazing! I'm a little sad you have to do `<Field name="foo.bar" …/>` and not `<Field.foo.bar …/>` but not having to declare the fields beforehand is also nice.

Great job!

**Comment by erikras** [comment]
@wmertens It turns out that React is not so happy about `<Something.another.other/>`. I think they have prohibited the dot syntax in JSX like that.

**Comment by gaearon** [comment]
>It turns out that React is not so happy about <Something.another.other/>. I think they have prohibited the dot syntax in JSX like that.

Are you sure? Works for me:

http://babeljs.io/repl/#?evaluate=true&presets=es2015%2Creact&experimental=false&loose=false&spec=false&code=%3CFoo.bar.wat%20%2F%3E

```js
<Foo.bar.wat />
```

```js
"use strict";

React.createElement(Foo.bar.wat, null);
```

**Comment by davidkpiano** [comment]
@gaearon I think he might be talking about getters rather than static properties? (If I remember correctly from the V5/6 proposal thread)

**Comment by erikras** [comment]
Okay, so my problem was not the dots; it was the lowercase. I was trying to do `<firstName.textarea/>`, and JSX wants to the component to be title case.

I _suppose_ something like `<Fields.contact.shipping.street.input/>`

And I do wonder if those dots could be done with a lazy getter... It might require some more research.

**Comment by gaearon** [comment]
>Okay, so my problem was not the dots; it was the lowercase. I was trying to do <firstName.textarea/>, and JSX wants to the component to be title case.

I think this is only true without dots. e.g. `<firstName />` will be assumed to be a custom (web) component. But `<firstName.input />` will work.

http://babeljs.io/repl/#?evaluate=true&presets=es2015%2Creact&experimental=false&loose=false&spec=false&code=%3CfirstName%20%2F%3E%3B%0A%3CfirstName.input%20%2F%3E%3B%0A%3Cprops.firstName.input%20%2F%3E%3B

```js
<firstName />;
<firstName.input />;
<props.firstName.input />;
```

```js
"use strict";

React.createElement("firstName", null);
React.createElement(firstName.input, null);
React.createElement(props.firstName.input, null);
```

**Comment by gaearon** [comment]
This also doesn’t print any warnings for me: https://jsfiddle.net/fvbaqb0t/

**Comment by gaearon** [comment]
Whether those are getters or static properties shouldn't matter because it happens at compilation time when we don't know that anyway.

**Comment by erikras** [comment]
Yep. [Works with getters](https://jsfiddle.net/fvbaqb0t/1/).

**Comment by gaearon** [comment]
Hopefully you don't have to rewrite v6 once again now :P

**Comment by wmertens** [comment]
I think this can totally work both ways, if you provide fields they will be set as getters for custom components, and if you use the name attribute you add fields ad-hoc?

**Comment by erikras** [comment]
@wmertens That was the original plan, with the field getters just being wrappers for the `Field` components. I'm having trouble convincing myself that it's worth the extra effort to provide the wrappers. Convince me. What is really gained?

**Comment by gaearon** [comment]
I’d say string-based APIs are a thing to avoid, in general, because of possible renames and implicit dependencies.

**Comment by erikras** [comment]
@gaearon Right, but the string field names have to be fed into the library at some point. Why better at the outer form level (root) than down at the field level (leaves of the tree)?

**Comment by davidkpiano** [comment]
@gaearon On the other hand, using string-based paths in an API are the simplest alternative to having to provide a getter and setter:

```js
// compare this...
<Field model="foo.bar">

// to this, which is the minimum API required for no strings
const barModel = {
  get: (state) => state.foo.bar,
  set: (state, value) => return { ...state, foo: { ...state.foo, bar: value } }
};

<Field model={barModel}>
```

**Comment by gaearon** [comment]
You know better! 👍 
I thought this was something desirable, but if not, then it’s not worth the hassle 😄 . Can add it later anyway.

**Comment by wmertens** [comment]
> Convince me. What is really gained?

@erikras the simplest way to implement it would be to walk the fields array and create properties on Field that are just `(props) => <Field {...props} name={name}/>`.

Advantages:
* You cannot misspell field names, that would result in undefined element errors
* Less typing, somewhat easier to read since the field names are in predictable locations

Disadvantages:
* Extra code to maintain
* Wrapper elements unless you make a FieldFactory

…hmm, I'm not really making a compelling case here :)

**Comment by erikras** [comment]
@wmertens I definitely think it's better looking code. I mean...
```js
<div>
  <firstName.text/>
  <firstName.error className="my-customer-error-class"/>
</div>
```
...is very pretty.

So I think it _will_ get implemented eventually, but maybe as a `6.x` feature release in the somewhat distant future.

**Comment by davidhtien** [comment]
I get really serious lag when typing in a textarea in my form, is there a way around this? I tried what as suggested here [https://github.com/erikras/redux-form/issues/293#issuecomment-157738158](url) but then nothing appears in the textarea when I type.

**Comment by gaearon** [comment]
This is tangential but make sure you're testing performance with production version of Reacf.

**Comment by jhabdas** [comment]
@davidhtien try changing `value` to `defaultValue` to force the hand.

**Comment by davidhtien** [comment]
@jhabdas that fixed it! thanks man!

**Comment by jhabdas** [comment]
@davidhtien You're welcome. Please note holding a key will no longer cause repeated keystrokes to occur. But it's progress.

**Comment by erikras** [comment]
The performance of [`v6.0.0-alpha-7`](https://github.com/erikras/redux-form/releases/tag/v6.0.0-alpha.7) looks really good, so I'm closing this issue.

**Comment by luisrudge** [comment]
Thanks @erikras <3
